#########################
# Static tool & environment definition paths
#########################
home_dir:
  /mnt/home/groups/nmrl/demo/CLUSTER/bact-cov-meta-etc/SARS-CoV2-pipe/
work_dir:
  /mnt/home/groups/nmrl/demo/CLUSTER/bact-cov-meta-etc/SARS-CoV2-pipe/temp/
subscript_path:
  /mnt/home/groups/nmrl/demo/CLUSTER/bact-cov-meta-etc/SARS-CoV2-pipe/subscripts


##############
# cov_assembly
##############
fastq_sif:
  /mnt/home/groups/nmrl/image_files/fastq_processing.sif
multiqc_sif:
  /mnt/home/groups/nmrl/image_files/fastq_screen.sif
processing_env: 
  /mnt/home/groups/nmrl/demo/CLUSTER/bact-cov-meta-etc/SARS-CoV2-pipe/config_files/conda_defs/local_environment.yml
assembly_subscripts:
  /mnt/home/groups/nmrl/demo/CLUSTER/bact-cov-meta-etc/SARS-CoV2-pipe/subscripts/assembly/
latest_id_file:
  /mnt/home/groups/nmrl/demo/CLUSTER/bact-cov-meta-etc/SARS-CoV2-pipe/resources/assembly/current_id
sample_template:
  '/mnt/home/groups/nmrl/demo/CLUSTER/bact-cov-meta-etc/SARS-CoV2-pipe/resources/assembly/sample_template.json'


#########################
# cov_assembly configuration
#########################
#cutadapt (QC)
cutadapt:
  forward_adapter: AGATCGGAAGAGCACACGTCTGAACTCCAGTCA
  reverse_adapter: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT

#fastp (QC)
fastp:
  fastp_length_filter: 50
  fastp_quality_filter: 30

#bwa (read alignment)
bwa-mem:
  reference_path: /mnt/home/groups/nmrl/demo/CLUSTER/bact-cov-meta-etc/SARS-CoV2-pipe/resources/reference_genomes/sars_cov2/MN908947_3.fa
  bwa_verbose_level: 3

#ivar
ivar:
  ##primer_trimming
  primer_path: /mnt/home/groups/nmrl/demo/CLUSTER/bact-cov-meta-etc/SARS-CoV2-pipe/resources/primers/QIAseqDIRECTSARSCoV2primersfinal.bed
    #/mnt/home/groups/nmrl/demo/CLUSTER/bact-cov-meta-etc/SARS-CoV2-pipe/resources/primers/QIAseq_SARSCOV2_primers_v3-13.04.2021.bed
    #/mnt/home/groups/nmrl/demo/CLUSTER/bact-cov-meta-etc/SARS-CoV2-pipe/resources/primers/SARSCOV2_primers_v4-29.03.2022.bed

  ##consensus_calling 
  use_upper_depth_limit: 0 #used by samtools by default (depth above 8000 is diplayed as 8000), not used if 0 is supplied
  cons_quality_filter: 30
  cons_min_variant_supporting_read_fraction: 0.5 #50%
  cons_min_coverage: 15

#abra (indel realignment)
abra:
# abra_jar_path: /mnt/home/groups/nmrl/demo/CLUSTER/bact-cov-meta-etc/SARS-CoV2-pipe/tools/abra-0.97-SNAPSHOT-jar-with-dependencies_singularity.jar
  abra_jar_path: /mnt/home/groups/nmrl/demo/CLUSTER/bact-cov-meta-etc/SARS-CoV2-pipe/tools/abra2-2.23.jar
  abra_memory_limit_gb: 8
  abra_rule_cpus: 12

picard:
  dedup_threshold: 1000000 #minimum reads per sample to run deduplication
  picard_jar_path: /mnt/home/groups/nmrl/demo/CLUSTER/bact-cov-meta-etc/SARS-CoV2-pipe/tools/picard.jar

#qualimap (alignment QC)
qualimap:
  qualimap_sif_path: /mnt/home/groups/nmrl/image_files/qualimap_latest.sif
  qualimap_memory_limit_gb: 4

#freebayes (variant calling)
freebayes:
  quality_filter: 20
  coverage_depth_filter: 15

#snpEff (variant annotation)
snpEff:
  snpEff_path: /mnt/home/groups/nmrl/demo/CLUSTER/bact-cov-meta-etc/SARS-CoV2-pipe/tools/snpEff/snpEff.jar
  snpEff_memory_limit_gb: 8
  snpEff_reference: MN908947

#fastq_screen
fastqscreen:
  fq_screen_config: db/db-fastq-screen/fastq_screen.conf
  read1_downsample_fraction: 5 #what part of reads will be screened against fqscreen db (expected denominator of a fraction, e.g. if 20% (1/5) of the reads needed, 5 is expected)
  read2_downsample_fraction: 5

#multiqc
multiqc:
  multiqc_threads: 12

pangolin:
  sif_path: /mnt/home/groups/nmrl/image_files/pangolin.sif
  threads: 20

###Filled by the wrapper
assembly_target_files:
output_directory:


