# .github/workflows/update_pangolin.yml
# Setting-up singularity: https://github.com/marketplace/actions/setup-singularity
# Crond schedule basics: https://www.digitalocean.com/community/tutorials/how-to-use-cron-to-automate-tasks-ubuntu-1804
# Run actions on cron schedule: https://docs.getnacelle.com/deployment/scheduled-builds-github-actions.html#add-the-webhook-url
# SSH copy: https://github.com/marketplace/actions/copy-via-ssh
# Encrypted secrets: https://docs.github.com/en/actions/security-guides/encrypted-secrets


name: Trigger pangolin image update on a CRON Schedule

on:
  schedule:
    # Runs "at 11 AM every sunday" (see https://crontab.guru)
    - cron: '30 13 * * 3'
jobs:
  build:
    name: Trigger pangolin image update
    runs-on: ubuntu-latest
    steps:
      - name: build the container 
        uses: actions/checkout@v2
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3
        run: singularity build --force --fakeroot pangolin.sif config_files/s_recipes/pangolin.recipe
      - name: scp to HPC
        uses: garygrossgarten/github-action-scp@release
        with:
          local: pangolin.sif
          remote: /mnt/home/groups/nmrl/image_files/
          host: ${{ secrets.HPC_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASS }}