# .github/workflows/update_pangolin.yml
# Setting-up singularity: https://github.com/marketplace/actions/setup-singularity
# Crond schedule basics: https://www.digitalocean.com/community/tutorials/how-to-use-cron-to-automate-tasks-ubuntu-1804
# Run actions on cron schedule: https://docs.getnacelle.com/deployment/scheduled-builds-github-actions.html#add-the-webhook-url
# SSH copy: https://github.com/marketplace/actions/copy-via-ssh
# Encrypted secrets: https://docs.github.com/en/actions/security-guides/encrypted-secrets

name: Trigger pangolin image update based on push to snakemake/pangolin_update.log

on:
 push:
   branches:  [ snakemake ]
   paths:
     - "config_files/pangolin_update.log"
     - .github/workflows/update_pangolin.yml
jobs:
  build:
    name: Trigger pangolin image update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3
      - name: build the container 
        run: | 
          singularity build --force --fakeroot pangolin.sif config_files/s_recipes/pangolin.recipe
          chmod 775 pangolin.sif
      - name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.HPC_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASS }}
          local: /home/runner/work/SARS-CoV2-pipe/SARS-CoV2-pipe/pangolin.sif
          remote: ${{ secrets.HOST_IMAGES }}pangolin.sif
